# Generated by Django 3.2.8 on 2022-01-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addressmodel',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.RemoveField(
            model_name='addressmodel',
            name='pincode',
        ),
        migrations.AddField(
            model_name='addressmodel',
            name='name',
            field=models.CharField(default='', max_length=70),
        ),
    ]
