# Generated by Django 3.2.8 on 2022-01-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0002_auto_20220106_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressmodel',
            name='name',
            field=models.CharField(max_length=70),
        ),
    ]
