# Generated by Django 3.2.8 on 2022-01-07 11:15

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0004_studentmodel_studentmodel1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
        migrations.DeleteModel(
            name='StudentModel',
        ),
        migrations.DeleteModel(
            name='StudentModel1',
        ),
    ]
