# Generated by Django 3.2.8 on 2022-01-07 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0005_auto_20220107_1645'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
