# Generated by Django 3.2.8 on 2022-01-10 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0008_auto_20220110_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='Country',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='new_app.country'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='new_app.state'),
        ),
        migrations.AddField(
            model_name='district',
            name='Country',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='new_app.country'),
        ),
    ]
