# Generated by Django 3.2.8 on 2022-01-10 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0009_auto_20220111_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='Country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_app.country'),
        ),
        migrations.AlterField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_app.state'),
        ),
        migrations.AlterField(
            model_name='district',
            name='Country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_app.country'),
        ),
    ]
