# Generated by Django 3.2.8 on 2022-01-11 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0010_auto_20220111_0206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='Country',
        ),
        migrations.RemoveField(
            model_name='district',
            name='state',
        ),
        migrations.RemoveField(
            model_name='state',
            name='Country',
        ),
        migrations.RemoveField(
            model_name='studentaddress',
            name='city',
        ),
        migrations.RemoveField(
            model_name='studentaddress',
            name='country',
        ),
        migrations.RemoveField(
            model_name='studentaddress',
            name='district',
        ),
        migrations.RemoveField(
            model_name='studentaddress',
            name='state',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='State',
        ),
        migrations.DeleteModel(
            name='StudentAddress',
        ),
    ]
